# Generated by Django 2.2 on 2020-01-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='utype',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], default='User', max_length=15),
            preserve_default=False,
        ),
    ]
