# Generated by Django 2.2.3 on 2020-02-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_usermodel_utype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='utype',
        ),
    ]
