# Generated by Django 2.2 on 2020-02-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_auto_20200211_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='name',
        ),
    ]
