# Generated by Django 2.2 on 2020-01-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodIdfk', models.IntegerField()),
                ('userIdfk', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('address', models.TextField()),
                ('totalamt', models.IntegerField()),
            ],
            options={
                'db_table': 'order_tbl',
            },
        ),
    ]
