# Generated by Django 2.2 on 2020-01-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_auto_20200121_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='emailIdfk',
            field=models.EmailField(max_length=254),
        ),
    ]
